version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo cleaning up
      - aws s3 rm --recursive "s3://www.eyegive.org/"
  build:
    commands:
      - echo Nothing to do
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  base-directory: internationaleyeinstitute.org
